package gui;

import factories.MySQL_HorarioBusDAO;
import factories.MySQL_HorarioBusSelectDAO;
import factories.MySQL_PasajeDAO;
import factories.MySQL_PasajeBorradoSelectDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.HorarioBus;
import model.HorarioBusSelect;
import model.Pasaje;
import model.PasajeBorradoSelect;
import model.TMBus;
import model.TMHistorialPasajes;

public class App extends javax.swing.JFrame {

    private MySQL_HorarioBusSelectDAO listaBus;
    private MySQL_PasajeBorradoSelectDAO listaHisto;
    int numAsi;
    int asiento;
    List<Pasaje> listaAsientos;
    int limite = 2;
    String horario;
    String precio;
    String destino;

    public App() {
        initComponents();
        try {
            listaBus = new MySQL_HorarioBusSelectDAO();
            listaHisto = new MySQL_PasajeBorradoSelectDAO();
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(null);
        jPanel4.setVisible(true);
        jPanel4.setBackground(Color.DARK_GRAY);
        jPanel3.setBackground(Color.BLACK);
        jPanel5.setVisible(true);
        jPanel5.setBackground(Color.LIGHT_GRAY);
        FrameVenta.setBounds(0, 100, 800, 630);
        FrameVenta.setLocationRelativeTo(null);
        FrameHistorial.setBounds(0, 0, 800, 600);
        FrameHistorial.setLocationRelativeTo(null);
        txtTarifa.setEditable(false);
        txtHoraSalida.setEditable(false);
        txtDestino.setEditable(false);
        

        try {
            cargarTabla();
            colorAsientos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameVenta = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblAciento1 = new javax.swing.JLabel();
        lblAciento5 = new javax.swing.JLabel();
        lblAciento9 = new javax.swing.JLabel();
        lblAciento13 = new javax.swing.JLabel();
        lblAciento17 = new javax.swing.JLabel();
        lblAciento21 = new javax.swing.JLabel();
        lblAciento25 = new javax.swing.JLabel();
        lblAciento29 = new javax.swing.JLabel();
        lblAciento2 = new javax.swing.JLabel();
        lblAciento6 = new javax.swing.JLabel();
        lblAciento10 = new javax.swing.JLabel();
        lblAciento14 = new javax.swing.JLabel();
        lblAciento18 = new javax.swing.JLabel();
        lblAciento22 = new javax.swing.JLabel();
        lblAciento26 = new javax.swing.JLabel();
        lblAciento30 = new javax.swing.JLabel();
        lblAciento3 = new javax.swing.JLabel();
        lblAciento7 = new javax.swing.JLabel();
        lblAciento11 = new javax.swing.JLabel();
        lblAciento15 = new javax.swing.JLabel();
        lblAciento19 = new javax.swing.JLabel();
        lblAciento23 = new javax.swing.JLabel();
        lblAciento27 = new javax.swing.JLabel();
        lblAciento4 = new javax.swing.JLabel();
        lblAciento8 = new javax.swing.JLabel();
        lblAciento12 = new javax.swing.JLabel();
        lblAciento16 = new javax.swing.JLabel();
        lblAciento20 = new javax.swing.JLabel();
        lblAciento24 = new javax.swing.JLabel();
        lblAciento28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumAciento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblIdHorario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnTerminarVenta = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        FrameHistorial = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnVolverHistorial = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuses = new javax.swing.JTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venta De Pasajes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        jPanel4.setForeground(new java.awt.Color(255, 0, 51));

        lblAciento1.setText("1");
        lblAciento1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento5.setText("5");
        lblAciento5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento9.setText("9");
        lblAciento9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento13.setText("13");
        lblAciento13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento17.setText("17");
        lblAciento17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento21.setText("21");
        lblAciento21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento25.setText("25");
        lblAciento25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento29.setText("29");
        lblAciento29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento2.setText("2");
        lblAciento2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento6.setText("6");
        lblAciento6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento10.setText("10");
        lblAciento10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento14.setText("14");
        lblAciento14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento18.setText("18");
        lblAciento18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento22.setText("22");
        lblAciento22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento26.setText("26");
        lblAciento26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento30.setText("30");
        lblAciento30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento3.setText("3");
        lblAciento3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento7.setText("7");
        lblAciento7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento11.setText("11");
        lblAciento11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento15.setText("15");
        lblAciento15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento19.setText("19");
        lblAciento19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento23.setText("23");
        lblAciento23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento27.setText("27");
        lblAciento27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento4.setText("4");
        lblAciento4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento8.setText("8");
        lblAciento8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento12.setText("12");
        lblAciento12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento16.setText("16");
        lblAciento16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento20.setText("20");
        lblAciento20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento24.setText("24");
        lblAciento24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAciento28.setText("28");
        lblAciento28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAciento28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAciento29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAciento25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblAciento21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAciento17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblAciento5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAciento1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAciento9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAciento13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAciento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblAciento14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAciento27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAciento23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAciento19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAciento7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAciento11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(lblAciento15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAciento3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAciento4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblAciento16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAciento28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAciento4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAciento3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAciento2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(lblAciento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciento29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAciento30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wheel32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("VENTA PASAJE");

        jLabel3.setText("N° ACIENTO:");

        txtNumAciento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumAcientoKeyTyped(evt);
            }
        });

        jButton1.setText("Vender Pasaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("TARIFA: ");

        jLabel5.setText("HORA SALIDA: ");

        jLabel6.setText("DESTINO: ");

        jLabel7.setText("$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(txtNumAciento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumAciento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jButton2.setText("Volver Horario Buses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnTerminarVenta.setText("Terminar Venta");
        btnTerminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarVentaActionPerformed(evt);
            }
        });

        btnHistorial.setText("Ver Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnTerminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorial)
                .addContainerGap())
        );

        javax.swing.GroupLayout FrameVentaLayout = new javax.swing.GroupLayout(FrameVenta.getContentPane());
        FrameVenta.getContentPane().setLayout(FrameVentaLayout);
        FrameVentaLayout.setHorizontalGroup(
            FrameVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameVentaLayout.setVerticalGroup(
            FrameVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("HISTORIAL");

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblHistorial);

        btnVolverHistorial.setText("VOLVER");
        btnVolverHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jLabel8))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(btnVolverHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnVolverHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout FrameHistorialLayout = new javax.swing.GroupLayout(FrameHistorial.getContentPane());
        FrameHistorial.getContentPane().setLayout(FrameHistorialLayout);
        FrameHistorialLayout.setHorizontalGroup(
            FrameHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameHistorialLayout.setVerticalGroup(
            FrameHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horario de Buses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tblBuses.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblBusesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuses);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusesMouseReleased
        try {
            if (evt.getClickCount() == 2) {

                FrameVenta.setVisible(true);

                this.setVisible(false);

                int fila = tblBuses.getSelectedRow();

                TMBus id_Bus = (TMBus) tblBuses.getModel();

                lblIdHorario.setText(String.valueOf(fila + 1));
                
                
                int i = tblBuses.getSelectedRow(); 
                horario = tblBuses.getValueAt(i,1).toString();
                System.out.println("Buses:"+ horario);
                precio = tblBuses.getValueAt(i, 3).toString();
                destino = tblBuses.getValueAt(i, 2).toString();
                
                txtNumAciento.requestFocus();
                txtHoraSalida.setText(horario);
                txtTarifa.setText(precio);
                txtDestino.setText(destino);
                
                
                
                

                asientosVendidos();

                lblIdHorario.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblBusesMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            MySQL_PasajeDAO nuevo = new MySQL_PasajeDAO();
            Pasaje p = new Pasaje();

            numAsi = Integer.valueOf(txtNumAciento.getText());
            int id_Horario = Integer.valueOf(lblIdHorario.getText());

            p.setAsiento(numAsi);
            p.setFk_horario(id_Horario);

            nuevo.create(p);

            txtNumAciento.setText(null);
            txtNumAciento.requestFocus();
            asientosVendidos();
            
            
            JOptionPane.showMessageDialog(this, "Pasaje Vendido", "VENDIDO", HEIGHT);
            JOptionPane.showMessageDialog(this, "Numero de Asiento: "+numAsi+ 
                    "\n\n Horario: "+horario,"Pasaje Vendido ", HEIGHT);

        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrameVenta.setVisible(false);
        this.setVisible(true);
        colorAsientos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNumAcientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumAcientoKeyTyped
        int k = (int) evt.getKeyChar();
        if (txtNumAciento.getText().length()== limite){
            evt.consume();
        }
        
        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 241 || k == 209) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
           //transfiere el foco si presionas enter
            txtNumAciento.transferFocus();
        }
    }//GEN-LAST:event_txtNumAcientoKeyTyped

    private void btnTerminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarVentaActionPerformed
        try {
            int id_horario;
            id_horario = Integer.parseInt(lblIdHorario.getText());
            
            MySQL_PasajeDAO eliminar = new MySQL_PasajeDAO();
            
            eliminar.delete(id_horario);
            colorAsientos();
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTerminarVentaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        try {
            cargarTablaHistorial();
            
            FrameHistorial.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnVolverHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHistorialActionPerformed
        FrameHistorial.setVisible(false);
    }//GEN-LAST:event_btnVolverHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameHistorial;
    private javax.swing.JFrame FrameVenta;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnTerminarVenta;
    private javax.swing.JButton btnVolverHistorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    javax.swing.JLabel lblAciento1;
    private javax.swing.JLabel lblAciento10;
    private javax.swing.JLabel lblAciento11;
    private javax.swing.JLabel lblAciento12;
    private javax.swing.JLabel lblAciento13;
    private javax.swing.JLabel lblAciento14;
    private javax.swing.JLabel lblAciento15;
    private javax.swing.JLabel lblAciento16;
    private javax.swing.JLabel lblAciento17;
    private javax.swing.JLabel lblAciento18;
    private javax.swing.JLabel lblAciento19;
    private javax.swing.JLabel lblAciento2;
    private javax.swing.JLabel lblAciento20;
    private javax.swing.JLabel lblAciento21;
    private javax.swing.JLabel lblAciento22;
    private javax.swing.JLabel lblAciento23;
    private javax.swing.JLabel lblAciento24;
    private javax.swing.JLabel lblAciento25;
    private javax.swing.JLabel lblAciento26;
    private javax.swing.JLabel lblAciento27;
    private javax.swing.JLabel lblAciento28;
    private javax.swing.JLabel lblAciento29;
    private javax.swing.JLabel lblAciento3;
    private javax.swing.JLabel lblAciento30;
    private javax.swing.JLabel lblAciento4;
    private javax.swing.JLabel lblAciento5;
    private javax.swing.JLabel lblAciento6;
    private javax.swing.JLabel lblAciento7;
    private javax.swing.JLabel lblAciento8;
    private javax.swing.JLabel lblAciento9;
    private javax.swing.JLabel lblIdHorario;
    private javax.swing.JTable tblBuses;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtNumAciento;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() throws ClassNotFoundException {
        try {
            List<HorarioBusSelect> listaBuses = this.listaBus.read();
            TMBus tm = new TMBus(listaBuses);
            tblBuses.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cargarTablaHistorial() throws ClassNotFoundException{
        try {
            int id_histo;
            id_histo = Integer.parseInt(lblIdHorario.getText());
            
            List<PasajeBorradoSelect> listaHistorial = this.listaHisto.read(id_histo);
            TMHistorialPasajes tmhp = new TMHistorialPasajes(listaHistorial);
            tblHistorial.setModel(tmhp);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void asientosVendidos() throws SQLException, ClassNotFoundException {
        MySQL_PasajeDAO asiento = new MySQL_PasajeDAO();
        
        int id_Horario = Integer.valueOf(lblIdHorario.getText());

                listaAsientos = new ArrayList<>();

                listaAsientos = asiento.numAsiento(id_Horario);

                System.out.println(listaAsientos);
                for (Pasaje p : listaAsientos) {
                    System.out.println(p);
                    if (p.getAsiento() == 1) {
                        lblAciento1.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 2) {
                        lblAciento2.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 3) {
                        lblAciento3.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 4) {
                        lblAciento4.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 5) {
                        lblAciento5.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 6) {
                        lblAciento6.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 7) {
                        lblAciento7.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 8) {
                        lblAciento8.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 9) {
                        lblAciento9.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 10) {
                        lblAciento10.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 11) {
                        lblAciento11.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 12) {
                        lblAciento12.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 13) {
                        lblAciento13.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 14) {
                        lblAciento14.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 15) {
                        lblAciento15.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 16) {
                        lblAciento16.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 17) {
                        lblAciento17.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 18) {
                        lblAciento18.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 19) {
                        lblAciento19.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 20) {
                        lblAciento20.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 21) {
                        lblAciento21.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 22) {
                        lblAciento22.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 23) {
                        lblAciento23.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 24) {
                        lblAciento24.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 25) {
                        lblAciento25.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 26) {
                        lblAciento26.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 27) {
                        lblAciento27.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 28) {
                        lblAciento28.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 29) {
                        lblAciento29.setBackground(Color.RED);
                    }
                    if (p.getAsiento() == 30) {
                        lblAciento30.setBackground(Color.RED);
                    }

                }
    }

    private void colorAsientos() {
        lblAciento1.setBackground(Color.GREEN);
        lblAciento2.setBackground(Color.GREEN);
        lblAciento3.setBackground(Color.GREEN);
        lblAciento4.setBackground(Color.GREEN);
        lblAciento5.setBackground(Color.GREEN);
        lblAciento6.setBackground(Color.GREEN);
        lblAciento7.setBackground(Color.GREEN);
        lblAciento8.setBackground(Color.GREEN);
        lblAciento9.setBackground(Color.GREEN);
        lblAciento10.setBackground(Color.GREEN);
        lblAciento11.setBackground(Color.GREEN);
        lblAciento12.setBackground(Color.GREEN);
        lblAciento13.setBackground(Color.GREEN);
        lblAciento14.setBackground(Color.GREEN);
        lblAciento15.setBackground(Color.GREEN);
        lblAciento16.setBackground(Color.GREEN);
        lblAciento17.setBackground(Color.GREEN);
        lblAciento18.setBackground(Color.GREEN);
        lblAciento19.setBackground(Color.GREEN);
        lblAciento20.setBackground(Color.GREEN);
        lblAciento21.setBackground(Color.GREEN);
        lblAciento22.setBackground(Color.GREEN);
        lblAciento23.setBackground(Color.GREEN);
        lblAciento24.setBackground(Color.GREEN);
        lblAciento25.setBackground(Color.GREEN);
        lblAciento26.setBackground(Color.GREEN);
        lblAciento27.setBackground(Color.GREEN);
        lblAciento28.setBackground(Color.GREEN);
        lblAciento29.setBackground(Color.GREEN);
        lblAciento30.setBackground(Color.GREEN);

        lblAciento1.setOpaque(true);
        lblAciento2.setOpaque(true);
        lblAciento3.setOpaque(true);
        lblAciento4.setOpaque(true);
        lblAciento5.setOpaque(true);
        lblAciento6.setOpaque(true);
        lblAciento7.setOpaque(true);
        lblAciento8.setOpaque(true);
        lblAciento9.setOpaque(true);
        lblAciento10.setOpaque(true);
        lblAciento11.setOpaque(true);
        lblAciento12.setOpaque(true);
        lblAciento13.setOpaque(true);
        lblAciento14.setOpaque(true);
        lblAciento15.setOpaque(true);
        lblAciento16.setOpaque(true);
        lblAciento17.setOpaque(true);
        lblAciento18.setOpaque(true);
        lblAciento19.setOpaque(true);
        lblAciento20.setOpaque(true);
        lblAciento21.setOpaque(true);
        lblAciento22.setOpaque(true);
        lblAciento23.setOpaque(true);
        lblAciento24.setOpaque(true);
        lblAciento25.setOpaque(true);
        lblAciento26.setOpaque(true);
        lblAciento27.setOpaque(true);
        lblAciento28.setOpaque(true);
        lblAciento29.setOpaque(true);
        lblAciento30.setOpaque(true);
    }

}
